name: Run Cypress Test
on:
  push:
    branches:
      - 'main'   
      
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install a project with a clean slate
        run: |
          npm ci --force
          $(npm bin)/cypress cache path
          $(npm bin)/cypress cache list
          $(npm bin)/cypress verify
       
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/Scripts/Assignment6.cy.js
